---
title: "Yahoo Stock Volatility"
author: "Vishi Cline"
date: "November 13, 2016"
output: 
  html_document: 
    keep_md: true 
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install Packages
```{r , echo=FALSE}
#install.packages("tseries")
library(tseries)
```

# Download Data
```{r , echo=TRUE}
SNPdata<-get.hist.quote(instrument = 'TCP',quote="Close")
length(SNPdata)
```

# Calculate Log Returns
```{r , echo=TRUE}
SNPret<-log(lag(SNPdata))-log(SNPdata)
length(SNPret)
```

# Calculate Volatility measure
```{r , echo=TRUE}
SNPvol<-sd(SNPret) * sqrt(250)*100
SNPvol
```

# Calculate volatility and a continuous lookback window using various decay factors.
```{r , echo=TRUE}
Vol<-function(d,logrets){
  var=0
  lam=0
  varlist<-c()
  for (r in logrets){
    lam=lam*(1-1/d)+1
    var=(1-1/lam)*var+(1/lam)*r^2
    varlist<-c(varlist,var)
  }
  sqrt(varlist)
}

#volatility with different weights
volest<-Vol(10, SNPret)
volest2<-Vol(30, SNPret)
volest3<-Vol(100, SNPret)
```

# Plot the results
```{r , echo=TRUE}
plot(volest, type="l")
lines(volest2, type="l", col="red")
lines(volest3, type="l", col="blue")
```